# Generated by Django 5.1.3 on 2024-11-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolas',
            name='imagen',
        ),
    ]
